---

all:
  children:
    consul_servers:
      vars:
        ansible_user      : playground
        ansible_ssh_pass  : # Add server password
        ansible_sudo_pass : # Add server password
      hosts:
        0.0.0.0:
    consul_clients:
      vars: 
        ansible_user: playground
        ansible_ssh_pass  : # Add server password
        ansible_sudo_pass : # Add server password
      hosts:
        0.0.0.0: